@host = http://127.0.0.1:6000/v1/users

GET {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzMDU1Njc3fQ.sWH4uAz01LtPqYfY0-LLN5DAQ6TWMTKJuVrFY8CfcoQ HTTP/1.1


### Create
POST {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzMDU1Njc3fQ.sWH4uAz01LtPqYfY0-LLN5DAQ6TWMTKJuVrFY8CfcoQ HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "username": "Harry Potter",
    "password": "gryffindor"
}


### Update
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 6,
    "username": "Leni Robredo",
    "password": "kakampink"
}


### Delete cats
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json

[10]



### Get 1
GET {{host}}/?fields=username HTTP/1.1


### Update 1
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
  "id": 0, 
  "username": "Albus Dumbledore",
  "password": "hogwarts"
}


### Delete 1
DELETE {{host}}/ HTTP/1.1
