@host = http://127.0.0.1:6000/v1/cats

GET {{host}}/?fields=name&offset=0&limit=2 HTTP/1.1


### Create
POST {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Guccigoo"
}


### Update
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 19,
    "name": "Pradading"
}


### Delete cats
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json

[21,23,12,16,17]



### Get 1
GET {{host}}/24?fields=id HTTP/1.1


### Update 1
PUT {{host}}/22 HTTP/1.1
Content-Type: application/json

{
  "id": 0, 
  "name": "Crookshankies"
}


### Delete 1
DELETE {{host}}/22 HTTP/1.1
